#!/bin/bash


function container_install {


echo ''
echo -e '\033[1;32m To start the installation, Docker must be installed beforehand.'
echo -e '\033[1;32m If Docker is already installed, you can initiate the installation by using the install option,' 
echo -e '\033[1;32m which allows for installation via a Dockerfile, or by using the pull option,'
echo -e '\033[1;32m which retrieves a pre-built Docker image.'
echo ''
echo -e '\033[1;32m If you need help click ------>  \e]8;;https://docs.docker.com/engine/install/\e\\How to install docker?\e]8;;\e\\ [https://docs.docker.com/engine/install/]'

echo ''
echo -e '\033[1;36m Select option:'
echo ''
echo -e '\033[1;36m  -> Docker container installation [install]'
echo -e '\033[1;36m  -> Docker container pulling [pull]'
echo -e '\033[1;36m  -> Back [back]'
echo ''
		read con
		con=$(echo $con | tr '[:upper:]' '[:lower:]')

if [[ $con == 'install' ]]
then
	
	log_install=$(pwd)/setup/install.log.out
	
	sudo apt-get -y install unzip >> $log_install 2>&1
	sudo apt -y install python3.8  >> $log_install 2>&1
    sudo apt -y install python3-pip  >> $log_install 2>&1
	sudo pip3 install gdown >> $log_install 2>&1
    sudo apt-get update >> $log_install 2>&1
	
	cd setup 
	
	echo -e "\033[0;31m $(date) Localhost env preparing..."
	if [ -d "Drop-seq_tools-2.4.0" ]; then
	
    rm -rf Drop-seq_tools-2.4.0
    
	fi
	
	gdown 1deqNjK2Ix_O0yPQTnXqD6ShX2WYH5PAz
	unzip Drop-seq_tools-2.4.0.zip >> $log_install 2>&1
	rm -r Drop-seq_tools-2.4.0.zip >> $log_install 2>&1
	mv Drop-seq_tools-2.4.0 DropSeq >> $log_install 2>&1

	

	cd ..
	
	echo -e "\033[0;31m $(date) Docker build starting..."
	sudo DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_STEP_LOG_MAX_SIZE=10485760 --no-cache -t jseq -f Dockerfile .
	id=$(docker images --format "{{.ID}}" jseq)

	length=${#id}

	length=${#id}
	
	if [[ $length -ge 4 && $length -le 20 ]]; then
    	
		echo $id
		echo id=$id > $(pwd)/setup/docker_id
		docker run --privileged --rm -it -v $(pwd):/app/JSEQ_scRNAseq -e fun_run=True $id 
	else
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''
		echo -e '\033[1;31m The trouble with Docker'
		echo -e '\033[1;31m Check if Docker is running or even installed'
		echo -e '\033[1;31m If you have problems, read the README or don`t hesitate to contact us!'
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''

		starting_point

	fi
	
	
	
elif [[ $con == 'pull' ]]
then

    log_install=$(pwd)/setup/install.log.out
	
	sudo apt-get -y install unzip >> $log_install 2>&1
	sudo apt -y install python3.8  >> $log_install 2>&1
    sudo apt -y install python3-pip  >> $log_install 2>&1
	sudo pip3 install gdown >> $log_install 2>&1
    sudo apt-get update >> $log_install 2>&1
	
	cd setup 
	
	echo -e "\033[0;31m $(date) Localhost env preparing..."
	if [ -d "Drop-seq_tools-2.4.0" ]; then
	
    rm -rf Drop-seq_tools-2.4.0
    
	fi
	
	gdown 1deqNjK2Ix_O0yPQTnXqD6ShX2WYH5PAz
	unzip Drop-seq_tools-2.4.0.zip >> $log_install 2>&1
	rm -r Drop-seq_tools-2.4.0.zip >> $log_install 2>&1
	mv Drop-seq_tools-2.4.0 DropSeq >> $log_install 2>&1


	cd ..
	
	echo -e "\033[0;31m $(date) Docker pull starting..."
	sudo docker pull jkubis96/jseq_scrnaseq:jseq
	id=$(docker images --format "{{.ID}}" jkubis96/jseq_scrnaseq)
	
	length=${#id}
	
	if [[ $length -ge 4 && $length -le 20 ]]; then
    	
		echo $id
		echo id=$id > $(pwd)/setup/docker_id
		docker run --privileged --rm -it -v $(pwd):/app/JSEQ_scRNAseq -e fun_run=True $id 
	else
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''
		echo -e '\033[1;31m The trouble with Docker'
		echo -e '\033[1;31m Check if Docker is running or even installed'
		echo -e '\033[1;31m If you have problems, read the README or don`t hesitate to contact us!'
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''

		starting_point

	fi
	
	
	
elif [[ $con == 'back' ]]
then

    starting_point
	
else 
		container_install
fi

}



function starting_point {

files_1=$(pwd)/requirements_file/
files_2=$(pwd)/scripts/

for file in "$files_1"/*; do
    if [[ -f "$file" && "$file" != *.xlsx ]]; then
        if grep -q $'\r' "$file"; then
            sed -i 's/\r$//' "$file"
        fi
    fi
done

for file in "$files_2"/*; do
    if [[ -f "$file" ]]; then
        if grep -q $'\r' "$file"; then
            sed -i 's/\r$//' "$file"
        fi
    fi
done



echo ''
echo -e '\033[1;33m Welcome to the JSEQ_scRNAseq© tool'
echo -e '\033[1;33m The pipeline was prepared at the Institute of Bioorganic Chemistry, Polish Academy of Sciences'
echo -e '\033[1;33m All information and references you can check README on GitHub'
echo -e '\033[1;33m Contact: jbiosystem@gmail.com or jakub.kubis1996@gmail.com'
echo ''
echo ''

echo -e '\033[1;36m Select option:'
echo ''
echo -e '\033[1;36m  -> Install [install]'
echo -e '\033[1;36m  -> Start program [start]'
echo -e '\033[1;36m  -> Exit [q]'
echo ''
	

echo ''
		read l
		l=$(echo $l | tr '[:upper:]' '[:lower:]')


if [[ $l == 'install' ]]
then

container_install
		
elif [[ $l == 'start' ]]
then
    
	if [[ -f $(pwd)/setup/docker_id ]];
	then

		source $(pwd)/setup/docker_id
		id=$id
		docker run --privileged --rm -it -v $(pwd):/app/JSEQ_scRNAseq -e fun_run=True $id 
	
	else
		
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''
		echo -e '\033[1;31m The JSEQ_scRNAseq© tool has not been installed'
		echo -e '\033[1;31m The tool must be installed before starting'
		echo -e '\033[1;31m Check if Docker is installed and install the JSEQ_scRNAseq© tool'
		echo -e '\033[1;31m If you have problems, read the README or don`t hesitate to contact us!'
		echo ''
		echo -e '\033[1;31m !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!'
		echo ''

		starting_point

	fi
	
elif [[ $l == 'q' ]]
then

	exit

else 
		starting_point
fi

}

starting_point



