#!/bin/bash 

echo ''
echo -e '\033[1;36m Docker container'

echo ''
echo ''

function start {

echo ''
echo -e '\033[1;36m Choose JSEQ function:'
echo -e '\033[1;36m -download RefGenome [genome]'
echo -e '\033[1;36m -creat new project [project]'
echo -e '\033[1;36m -start analysis [analysis]'
echo -e '\033[1;36m -quit [q]'
echo ''
echo -e '\033[1;36m Choose function:'
echo ''
	read s
	s=$(echo $s | tr '[:upper:]' '[:lower:]')


if [[ $s == 'genome' ]]
then
        source=$(pwd)/scripts/genome_indexing
		source $source
		GENOME
		
		
elif [[ $s == 'project' ]]
then
        source=$(pwd)/scripts/projects
		source $source
		PROJECT
		
elif [[ $s == 'analysis' ]]
then
		source=$(pwd)/scripts
		source $source/project_selection
		select_analysis
		
function experiment_selection {
		if [[ $d  == *'fq'* && $species  == 'human' ]] || [[ $d  == *'fq'* && $species  == 'mice' ]] || [[ $d  == *'fq'* && $species  == 'custom' ]];
then
		log=$(pwd)/projects/$project_name_mode/results/process.log.out
        source=$(pwd)/scripts
		source $source/analysis_species
		echo ''
		echo -e "\033[0;34m Process start..."
		echo ''
		echo -e "\033[1;33m WARNING! Depending on data set volume and data heterogeneity a whole analysis can last even several hours" 
		echo ''
		echo -e "\033[0;34m $(date) Trimming of the adapters and quality control of the reads"
		TRIMMING >> $log 2>&1
		echo -e "\033[0;34m $(date) UMIs and barcodes extraction"
		whitelist >> $log 2>&1
		echo -e "\033[0;34m $(date) Starting of the mapping process"
		STAR_MAPPING >> $log 2>&1
		echo -e "\033[0;34m $(date) Adding UMI and barcode tags to bam file"
		add_tags >> $log 2>&1	
		echo -e "\033[0;34m $(date) Annotation to transcriptome regions"
		dropSEQ >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing substitution errors in the cell barcodes"
		final_exon >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing barcode indexes synthesis errors"
		completed_bam >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating count statistics"
		umi_extract >> $log 2>&1
		umi_expression >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating RNA metrics"
		scRNAmetrics >> $log 2>&1
		metric_plot >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating matrix of counts"
		convert_mtx_umi >> $log 2>&1
		echo -e "\033[0;34m $(date) Counts analysis and creating report"
		seurat >> $log 2>&1
		echo ''
		echo -e "\033[0;32m Process completed"
		echo ''
		echo -e "\033[1;33m Check $project_name_mode for the results (REPORT). If you don't see the REPORT file, so check process.log file for some errors"
		echo ''
		
elif
		[[ $d  == *'_fq'* ]] && [[ $species  == 'mix' ]];
then
		log=$(pwd)/projects/$project_name_mode/results/process.log.out
		
        source=$(pwd)/scripts
		source $source/analysis_mix
		echo ''
		echo -e "\033[0;34m Process start..."
		echo ''
		echo -e "\033[1;33m WARNING! Depending on data set volume and data heterogeneity a whole analysis can last even several hours" 
		echo ''
		echo -e "\033[0;34m $(date) Trimming of the adapters and quality control of the reads"
		directory >> $log 2>&1
		TRIMMING >> $log 2>&1
		echo -e "\033[0;34m $(date) UMIs and barcodes extraction"
		whitelist >> $log 2>&1
		echo -e "\033[0;34m $(date) Starting of the mapping process"
		STAR_MAPPING >> $log 2>&1
		echo -e "\033[0;34m $(date) Adding UMI and barcode tags to bam file"
		add_tags >> $log 2>&1			
		echo -e "\033[0;34m $(date) Annotation to transcriptome regions"
		dropSEQ >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing substitution errors in the cell barcodes"
		final_exon >> $log 2>&1
		echo -e "\033[0;34m $(date) Detecting and repairing barcode indexes synthesis errors"
		completed_bam >> $log 2>&1
		echo -e "\033[0;34m $(date) Dividing combined scingle cell data to mice and human experiments analysis"
		filtr_mice >> $log 2>&1
		filtr_human >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating count statistics"
		umi_extract >> $log 2>&1
		umi_expression_mice >> $log 2>&1
		umi_expression_human >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating metrics of the genetics parts content"
		scRNAmetrics_mice >> $log 2>&1
		scRNAmetrics_human >> $log 2>&1
		metric_plot_mice >> $log 2>&1
		metric_plot_human >> $log 2>&1
		echo -e "\033[0;34m $(date) Creating matrix of counts"
		convert_mtx_umi_mice >> $log 2>&1
		convert_mtx_umi_human >> $log 2>&1
		echo -e "\033[0;34m $(date) Counts analysis and creating report"	
		seurat_mix >> $log 2>&1
		echo ''
		echo -e "\033[0;32m Process completed"
		echo ''
		echo -e "\033[1;33m Check $project_name_mode for the results (REPORT). If you don't see the REPORT file, so check process.log file for some errors"
		echo ''
		
elif	[[ $species  == 'human' && $d  == *'_exp'* ]] || [[ $species  == 'mice' && $d  == *'_exp'* ]] || [[ $species  == 'mix' && $d  == *'_exp'* ]] || [[ $species  == 'custom' && $d  == *'_exp'* ]]
then

		log=$(pwd)/projects/$project_name_mode/results/process.log.out
		
		source=$(pwd)/scripts
		source $source/seurat_analysis
		echo ''
		echo -e "\033[0;34m Process start..."
		echo ''
		echo -e "\033[1;33m WARNING! Depending on data set volume and data heterogeneity a whole analysis can last even several hours" 
		echo ''
		echo -e "\033[0;34m $(date) Counts analysis and creating report"	
		seurat_start >> $log 2>&1
		echo ''
		echo -e "\033[0;32m Process completed"
		echo ''
		echo -e "\033[1;33m Check $project_name_mode for the results (REPORT). If you don't see the REPORT file, so check process.log file for some errors"
		echo ''
else
        echo ''
		echo -e "\033[0;31m Experiment failed - check all the data from project"
		echo ''
		start
fi
}

experiment_selection

elif [[ $s == 'q' ]]
then
        exit
		
else
        start
fi


}

start