#!/bin/bash


function GENOME {

echo 'Enter the species [human/mice/mix]:'
echo ''

read species
species=$(echo $species | tr '[:upper:]' '[:lower:]')
source=$(pwd)/scripts/merge_genome.py
input_mice=$(pwd)/genome/$species/correct.annotation.mice.gtf
input_human=$(pwd)/genome/$species/correct.annotation.human.gtf
output_mix=$(pwd)/genome/$species/annotation.mix.gtf


if [[ $species == 'human' ]]
then

        mkdir -p genome
		mkdir -p genome/$species
        cd genome/$species
        wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.chr_patch_hapl_scaff.annotation.gtf.gz -O annotation.gtf.gz
	gunzip annotation.gtf.gz
	cat annotation.gtf | grep -E '3prime_overlapping_ncRNA|antisense|bidirectional_promoter_lncRNA|IG_C_gene|IG_C_pseudogene|IG_D_gene|IG_J_gene|IG_J_pseudogene|IG_pseudogene|IG_V_gene|IG_V_pseudogene|lincRNA|macro_lncRNA|miRNA|misc_RNA|Mt_rRNA|Mt_tRNA|non_coding|polymorphic_pseudogene|processed_pseudogene|processed_transcript|protein_coding|pseudogene|ribozyme|rRNA|scaRNA|scRNA|sense_intronic|sense_overlapping|snoRNA|snRNA|sRNA|TEC|transcribed_processed_pseudogene|transcribed_unitary_pseudogene|transcribed_unprocessed_pseudogene|translated_processed_pseudogene|TR_C_gene|TR_D_gene|TR_J_gene|TR_J_pseudogene|TR_V_gene|TR_V_pseudogene|unitary_pseudogene|unprocessed_pseudogene|vaultRNA' > correct.annotation.gtf
	rm annotation.gtf
	wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/GRCh38.p13.genome.fa.gz -O genome.fa.gz
	gunzip genome.fa.gz
	cd ..
	cd ..
	
start

elif [[ $species == 'mice' ]]
then
		mkdir -p genome
        mkdir -p genome/$species
        cd genome/$species
		
        wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.chr_patch_hapl_scaff.basic.annotation.gtf.gz -O annotation.gtf.gz
	gunzip annotation.gtf.gz
	cat annotation.gtf | grep -E '3prime_overlapping_ncRNA|antisense|bidirectional_promoter_lncRNA|IG_C_gene|IG_C_pseudogene|IG_D_gene|IG_J_gene|IG_J_pseudogene|IG_pseudogene|IG_V_gene|IG_V_pseudogene|lincRNA|macro_lncRNA|miRNA|misc_RNA|Mt_rRNA|Mt_tRNA|non_coding|polymorphic_pseudogene|processed_pseudogene|processed_transcript|protein_coding|pseudogene|ribozyme|rRNA|scaRNA|scRNA|sense_intronic|sense_overlapping|snoRNA|snRNA|sRNA|TEC|transcribed_processed_pseudogene|transcribed_unitary_pseudogene|transcribed_unprocessed_pseudogene|translated_processed_pseudogene|TR_C_gene|TR_D_gene|TR_J_gene|TR_J_pseudogene|TR_V_gene|TR_V_pseudogene|unitary_pseudogene|unprocessed_pseudogene|vaultRNA' > correct.annotation.gtf
	rm annotation.gtf
	wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.p6.genome.fa.gz -O genome.fa.gz
	gunzip genome.fa.gz
	cd ..
	cd ..

start

elif [[ $species == 'mix' ]]
then
		mkdir -p genome
		mkdir -p genome/$species
        cd genome/$species
        
		wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.chr_patch_hapl_scaff.annotation.gtf.gz -O annotation.human.gtf.gz
	gunzip annotation.human.gtf.gz
	cat annotation.human.gtf | grep -E '3prime_overlapping_ncRNA|antisense|bidirectional_promoter_lncRNA|IG_C_gene|IG_C_pseudogene|IG_D_gene|IG_J_gene|IG_J_pseudogene|IG_pseudogene|IG_V_gene|IG_V_pseudogene|lincRNA|macro_lncRNA|miRNA|misc_RNA|Mt_rRNA|Mt_tRNA|non_coding|polymorphic_pseudogene|processed_pseudogene|processed_transcript|protein_coding|pseudogene|ribozyme|rRNA|scaRNA|scRNA|sense_intronic|sense_overlapping|snoRNA|snRNA|sRNA|TEC|transcribed_processed_pseudogene|transcribed_unitary_pseudogene|transcribed_unprocessed_pseudogene|translated_processed_pseudogene|TR_C_gene|TR_D_gene|TR_J_gene|TR_J_pseudogene|TR_V_gene|TR_V_pseudogene|unitary_pseudogene|unprocessed_pseudogene|vaultRNA' > correct.annotation.human.gtf
	rm annotation.human.gtf
	wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/GRCh38.p13.genome.fa.gz -O genome.human.fa.gz
	gunzip genome.human.fa.gz
	
		wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/gencode.vM25.chr_patch_hapl_scaff.basic.annotation.gtf.gz -O annotation.mice.gtf.gz
	gunzip annotation.mice.gtf.gz
	cat annotation.mice.gtf | grep -E '3prime_overlapping_ncRNA|antisense|bidirectional_promoter_lncRNA|IG_C_gene|IG_C_pseudogene|IG_D_gene|IG_J_gene|IG_J_pseudogene|IG_pseudogene|IG_V_gene|IG_V_pseudogene|lincRNA|macro_lncRNA|miRNA|misc_RNA|Mt_rRNA|Mt_tRNA|non_coding|polymorphic_pseudogene|processed_pseudogene|processed_transcript|protein_coding|pseudogene|ribozyme|rRNA|scaRNA|scRNA|sense_intronic|sense_overlapping|snoRNA|snRNA|sRNA|TEC|transcribed_processed_pseudogene|transcribed_unitary_pseudogene|transcribed_unprocessed_pseudogene|translated_processed_pseudogene|TR_C_gene|TR_D_gene|TR_J_gene|TR_J_pseudogene|TR_V_gene|TR_V_pseudogene|unitary_pseudogene|unprocessed_pseudogene|vaultRNA' > correct.annotation.mice.gtf
	rm annotation.mice.gtf
	wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M25/GRCm38.p6.genome.fa.gz -O genome.mice.fa.gz
	gunzip genome.mice.fa.gz
	
	cat genome.human.fa genome.mice.fa > genome.mix.fa
	
	
	python3 $source $input_mice $input_human $output_mix
	
	rm correct.annotation.human.gtf
	rm correct.annotation.mice.gtf
	rm genome.human.fa
	rm genome.mice.fa
	cd ..
	cd ..
	
	
fi

}



function INDEXING {



if [[ $species == 'human' ]]
then

echo ''
echo 'Start indexing'
echo ''

mkdir -p projects/$project_name_mod/$species/index
cpu=$(grep -c ^processor /proc/cpuinfo)
cpu=$cpu-2
DIR=$(pwd)/projects/$project_name_mod/$species/index
GENOME=$(pwd)/genome/$species

STAR --runThreadN $cpu  --runMode genomeGenerate --genomeDir $DIR  --genomeFastaFiles $GENOME/*.fa  --sjdbGTFfile $GENOME/*.gtf --sjdbOverhang $READS_LENGHT 

echo ''
echo 'Done'
echo ''

start

elif [[ $species == 'mice' ]]
then

echo ''
echo 'Start indexing'
echo ''

mkdir -p projects/$project_name_mod/$species/index
cpu=$(grep -c ^processor /proc/cpuinfo)
cpu=$cpu-2
DIR=$(pwd)/projects/$project_name_mod/$species/index
GENOME=$(pwd)/genome/$species


STAR --runThreadN $cpu  --runMode genomeGenerate --genomeDir $DIR  --genomeFastaFiles $GENOME/*.fa  --sjdbGTFfile $GENOME/*.gtf --sjdbOverhang $READS_LENGHT 

echo ''
echo 'Done'
echo ''

fi

}




