#!/bin/bash
 
function select_analysis {

echo 'Analysis of data for fastq analysis project [1]  counts / expression analysis project [2]:'
read p 
p=$(echo $p | tr '[:upper:]' '[:lower:]')

if [[ $p == '2' ]]
then

	select_project_seurat		
	
elif [[ $p == '1' ]]
then


	select_project_fastq

else
       select_analysis
fi

}


function select_project_seurat {

INFASTP=$(pwd)/projects/*'exp'*

select d in $INFASTP; do test -n "$d" && break; echo ">>> Invalid Selection"; done
cd $d
source config
project_name=$project_name
project_name_mode=$project_name_mode 
READS_LENGHT=$READS_LENGHT 
species=$species 
cell=$cell
marker_path=$marker_path

cd ..

cd ..

}


function select_project_fastq {

INFASTP=$(pwd)/projects/*'fq'*

select d in $INFASTP; do test -n "$d" && break; echo ">>> Invalid Selection"; done
cd $d
source config
project_name=$project_name
project_name_mode=$project_name_mode 
READS_LENGHT=$READS_LENGHT 
species=$species 
cell=$cell
marker_path=$marker_path

cd ..

cd ..

}