#!/bin/bash

function seurat_start {
	echo -e "\033[1;36m $(date) Start counts / expression analysis"

	PATH_PROJECT=$(pwd)/projects/$project_name_mode
	MARKERS=$marker_path

	SCRIPTS_EXTRACT=$(pwd)/scripts
	Rscript $SCRIPTS_EXTRACT/cluster_species.R $PATH_PROJECT $MARKERS $species $project_name $data $cell

	cp $SCRIPTS_EXTRACT/manual_analysis.R $PATH_PROJECT/results
	cp $SCRIPTS_EXTRACT/report_manual.Rmd $PATH_PROJECT/results

	rm -rf $PATH_PROJECT/results/figures/UMAP_subtypes_files

}
