#!/bin/bash

function permission {

echo ''
echo 'Write [sudo] to give installation permission'
echo ''

read permission_sudo

$permission_sudo apt-get update

}


#python installation

function python {
$permission_sudo apt install python3.8
$permission_sudo apt install python3-pip
 pip3 install pysam==0.16.0.1
 pip3 install biopython==1.78
 pip3 install umi_tools==1.0.1
}


#r installation

function r_base {

$permission_sudo apt-get update
$permission_sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
$permission_sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
$permission_sudo apt-get update
$permission_sudo apt-get install r-base
$permission_sudo apt-get upgrade
$permission_sudo apt-get install curl
$permission_sudo apt-get install openssl
$permission_sudo apt-get install libcurl4-openssl-dev
$permission_sudo apt-get install libhdf5-dev
$permission_sudo apt-get install libhdf5-serial-dev
$permission_sudo apt-get install h5utils
$permission_sudo apt-get install hdf5-tools
$permission_sudo apt-get install hdf5-helpers
$permission_sudo apt-get install -y r-cran-httr
$permission_sudo apt-get install -y r-cran-leiden
$permission_sudo apt-get install -y r-cran-igraph

$permission_sudo apt-get update

path=$(pwd)
Rscript $path/r_req.R

}


#java installation

function java {

#apt-get update
$permission_sudo apt install default-jdk

}

#SAMtools installation

function SAMtools {

$permission_sudo apt-get install -y samtools

}

#STAR installation

function STAR {

	$permission_sudo apt-get update
        git clone https://github.com/alexdobin/STAR.git
        cd STAR/source
        make STAR
        cd ..
		$permission_sudo apt install rna-star
}


#Installation fastp

function fastp {

git clone https://github.com/OpenGene/fastp.git

cd fastp
make
$permission_sudo apt install fastp
cd ..
}

#download DropSeq scripts

function DropSeq {

wget -O DropSeq.zip https://github.com/broadinstitute/Drop-seq/releases/download/v2.4.0/Drop-seq_tools-2.4.0.zip
unzip DropSeq
rm -r DropSeq.zip

}

#download picard scripts

function picard {

git clone https://github.com/broadinstitute/picard.git
cd picard/
./gradlew shadowJar
cd ..

}


